Hexagon: Added support for generating vgather instruction on versions >=v65
aankit-ca/Halide pull request #1
Opened 2018-08-13 17:58 UTC by aankit-ca

2018-08-13 23:16 UTC, pranavb-ca requested changes
This is good stuff and now this looks far better than before.

2018-08-13 23:16 UTC, pranavb-ca commented on src/Expr.h
> +    Vtcm,
Minor Nit: For the name, please consider VTCM as opposed to Vtcm as it is an abbreviation as opposed to Heap, Stack, Register etc.

2018-08-13 23:16 UTC, pranavb-ca commented on src/CodeGen_Posix.cpp
> +                   memory_type == MemoryType::Vtcm ||
VTCM is HVX specific, please consider some asserts to for the target here.

2018-08-13 23:16 UTC, pranavb-ca commented on src/CodeGen_Posix.cpp
> +            string malloc_nm = (memory_type == MemoryType::Vtcm) ?
There is a chance Dillon could suggest the following - Don't make this change yet, but just suggesting a possibility he could ask for the following.
Why not define new_expr as halide_vtcm_malloc and free_function as halide_vtcm_free in the Allocate node if the memory_type is VTCM.
`void visit(const Allocate *op)
 internal_assert(!op->new_expr && free_function.empty() && "VTCM cannot have custom allocator and deallocators\n");
 new_expr = Call::make(Int(32), "halide_vtcm_malloc", size);
 free_function = "halide_vtcm_free"
`

2018-08-13 23:16 UTC, pranavb-ca commented on src/CodeGen_Hexagon.cpp
> +        string suffix = (op->type.bits() == 16) ? ".h.h" : ".w.w";
Do you want to assert for other types?

2018-08-13 23:16 UTC, pranavb-ca commented on src/HexagonOptimize.cpp
> +class ScatterGatherGenerator : public IRMutator {
Please use IRMutator2. IRMutator is not preferred any more.

2018-08-13 23:16 UTC, pranavb-ca commented on src/HexagonOptimize.cpp
> +        if (op->index.as<Ramp>() || !alloc ||
Please consider breaking this up like so
`
if (!alloc || alloc->memory_type != MemoryType::Vtcm)
    return Expr();
if (op->index.as<Ramp>())
    return Expr();
internal_assert(is_one(op->predicate) && ty.is_vector() && !ty.bits() == 8);
`

2018-08-13 23:16 UTC, pranavb-ca commented on src/HexagonOptimize.cpp
> +        Expr index = mutate(ty.bits()/8 * op->index);
ty.bytes()

2018-08-13 23:16 UTC, pranavb-ca commented on src/HexagonOptimize.cpp
> +                          Call::PureIntrinsic);
Is PureIntrinsic correct? gather does affect memory and represents a scheduling barrier, right?

2018-08-13 23:16 UTC, pranavb-ca commented on src/runtime/hvx_128.ll
> +  %dst_base = ptrtoint i16* %dst_base_ptr to i32
We should consider using getelementptr for pointer arithmetic instead of ptrtoint because from my days of working on LLVM I remember that ptrtoint and inttoptr can throw off some optimizations. For now, don't make any changes until I talk to Krzysztof tomorrow to confirm this.

2018-08-15 16:26 UTC, pranavb-ca requested changes
Reviewed the sim changes this time.

2018-08-15 16:26 UTC, pranavb-ca commented on src/runtime/hexagon_remote/sim_hap_vtcm.cpp
> +const unsigned int TCM_BASE = 0xD800 << 16;
Did you get these constant values from the example that I had shared with you? Do we know it is ok to use these for our case?

2018-08-15 16:26 UTC, pranavb-ca commented on src/runtime/hexagon_remote/sim_hap_vtcm.cpp
> +    add_translation_extended(1, va, pa, page_size, xwru, cccc, asid, aa, vg);
From line 113 to 116, please add comments for what is is going on.

2018-08-15 16:26 UTC, pranavb-ca commented on src/runtime/hexagon_remote/sim_hap_vtcm.cpp
> +        if (list->addr == addr) {
Shouldn't this be `if (curr->add == addr)`

2018-08-15 16:26 UTC, pranavb-ca commented on src/runtime/hexagon_remote/sim_hap_vtcm.cpp
> +void addAndMerge(Node* &list, Node* a) {
Minor nit: It looks like addAndMerge is only needed for free_blocks. If so, why take a list argument? This is a minor point only though.

2018-08-16 11:16 UTC, aankit-ca commented on src/HexagonOptimize.cpp
> +        if (op->index.as<Ramp>() || !alloc ||
I've changes this: (!alloc || alloc->memory_type != MemoryType::Vtcm) to a separate if block. Is the assert right thing there? If we don't have have a 1 predicate it's still not an error but we just don't have to do anything.

2018-08-16 11:16 UTC, aankit-ca commented on src/CodeGen_Hexagon.cpp
> +        string suffix = (op->type.bits() == 16) ? ".h.h" : ".w.w";
added assert for 8 bits

2018-08-16 11:17 UTC, aankit-ca commented on src/CodeGen_Posix.cpp
> +                   memory_type == MemoryType::Vtcm ||
Added an assert at function start

2018-08-16 11:17 UTC, aankit-ca commented on src/Expr.h
> +    Vtcm,
Changed the name to VTCM

2018-08-16 11:17 UTC, aankit-ca commented on src/HexagonOptimize.cpp
> +class ScatterGatherGenerator : public IRMutator {
It was in the plan. The next commit should make this change too.

2018-08-16 11:17 UTC, aankit-ca commented on src/HexagonOptimize.cpp
> +        Expr index = mutate(ty.bits()/8 * op->index);
Done

2018-08-16 11:19 UTC, aankit-ca commented on src/HexagonOptimize.cpp
> +                          Call::PureIntrinsic);
Changing to intrinsic, although we use setDoesNotAccessMemory() for both Intrinsic and PureIntrinsic.

2018-08-16 11:20 UTC, aankit-ca commented on src/runtime/hvx_128.ll
> +  %dst_base = ptrtoint i16* %dst_base_ptr to i32
Hi Pranav, I was also wondering whether using GEP is wiser. Should i change this to GEP?

2018-08-16 11:24 UTC, aankit-ca commented on src/runtime/hexagon_remote/sim_hap_vtcm.cpp
> +const unsigned int TCM_BASE = 0xD800 << 16;
Yes. I borrowed the values from the example. It's better to know about the origin for these numbers. Eric did not reply to the last email. I'll send the mail again to confirm this.

2018-08-16 11:26 UTC, aankit-ca commented on src/runtime/hexagon_remote/sim_hap_vtcm.cpp
> +    add_translation_extended(1, va, pa, page_size, xwru, cccc, asid, aa, vg);
I did not add comments to the entire file. You'll find the comments in the next commit.

2018-08-16 11:28 UTC, aankit-ca commented on src/runtime/hexagon_remote/sim_hap_vtcm.cpp
> +void addAndMerge(Node* &list, Node* a) {
I just used this to give to flexibility to call addAndMerge on the used list as well if needed in future. I'll remove the argument and directly use the global variable.

2018-08-16 20:01 UTC, pranavb-ca commented on src/runtime/hvx_128.ll
> +  %dst_base = ptrtoint i16* %dst_base_ptr to i32
Yes, GEP is better.

2018-08-20 06:34 UTC, aankit-ca commented on src/CodeGen_Posix.cpp
> +            string malloc_nm = (memory_type == MemoryType::Vtcm) ?
Yes Pranav. This is a possibility. But in a case the user wants to use VTCM memory as a scratch buffer in that case it is better to have the logic in CodeGen_Posix as HexagonOptimize file deals with mostly Hexagon Optimizations and all the logic for allocation is present in this create allocation itself. But I agree with your concern, Dillon might ask us to move this to the IRMutator.

2018-08-20 06:37 UTC, aankit-ca commented on src/runtime/hvx_128.ll
> +  %dst_base = ptrtoint i16* %dst_base_ptr to i32
Thanks a lot Pranav. Changing this to GEP.

2018-08-20 09:46 UTC, aankit-ca reviewed
@pranavb-ca Hi Pranav, I've made changes as you requested. Please let me know if more changes are required.

2018-08-20 09:46 UTC, aankit-ca commented on src/runtime/hexagon_remote/sim_hap_vtcm.cpp
> +        if (list->addr == addr) {
Yes Pranav, this should be curr. Thanks for the catch.

2018-08-30 20:30 UTC, aankit-ca commented on src/CodeGen_Posix.cpp
> +            string malloc_nm = (memory_type == MemoryType::Vtcm) ?
I got that wrong last time. Understood about new_expr and free_functions much later. Should have seen the comment carefully.

2018-10-03 20:31 UTC, merged